# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
