# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja', '0002_dojos_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojos',
            name='desc',
        ),
        migrations.AddField(
            model_name='ninjas',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
